### ISSUE TITLE
DigitalCameraMock should check whether the flash is on or off

### ISSUE THREAD

**Issue by sdenel** [oreillymedia/building_maintainable_software#1]
Both in Java and C#, the mock DigitalCameraMock should contain a Boolean value to check the flash was actually turned off (by PerfectPicture).

**Comment by robvanderleek** [comment]
Thanks for your comment.
In the book we deliberately limited the amount of code in the mock class since we encourage developers to use mocking frameworks in these situations. Since the state of the flash is an implementation detail of DigitalCamara, in the test code based on the Mocking framework, we only check if a call to flashLightOn was made while taking the picture.
